.TH "AutoDestroyParticleSystem" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoDestroyParticleSystem \- Klasa automatycznie niszcząca particle system po zakończeniu jego animacji\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "\fIPobranie ParticleSystem\&. \fP"
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "\fIAutomatyczne zniszczenie particle system po zakończeniu jego animacji\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa automatycznie niszcząca particle system po zakończeniu jego animacji\&. 


.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void AutoDestroyParticleSystem\&.Start ()"

.PP
Pobranie ParticleSystem\&. 
.SS "void AutoDestroyParticleSystem\&.Update ()"

.PP
Automatyczne zniszczenie particle system po zakończeniu jego animacji\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
