.TH "ControllerPhysicsVolume2D" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControllerPhysicsVolume2D \- klasa \fBControllerPhysicsVolume2D\fP  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "\fBControllerParameters2D\fP \fBParameters\fP"
.br
.RI "\fIUzywane przy zmianie srodowiska w jakim jest gracz (np\&. na wode), co wplywa na parametry kontrolera\&. \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
klasa \fBControllerPhysicsVolume2D\fP 


.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "\fBControllerParameters2D\fP ControllerPhysicsVolume2D\&.Parameters"

.PP
Uzywane przy zmianie srodowiska w jakim jest gracz (np\&. na wode), co wplywa na parametry kontrolera\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
