.TH "FinishLevel" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FinishLevel \- Klasa odpowiedzialna za przejście do następnego poziomu, po wejściu w obszar zmiany poziomu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBOnTriggerEnter2D\fP (Collider2D other)"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "string \fBLevelName\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa odpowiedzialna za przejście do następnego poziomu, po wejściu w obszar zmiany poziomu\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
