.TH "FollowPath" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FollowPath \- klasa \fBFollowPath\fP  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Typy publiczne"

.in +1c
.ti -1c
.RI "enum \fBFollowType\fP { \fBMoveTowards\fP, \fBLerp\fP }
.RI "\fIWybor trybu ruchu\&. Lerp - wykorzystujacy interpolacje liniowa\&. \fP""
.br
.in -1c
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "\fIInicjalizacja\&. \fP"
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "\fBFollowType\fP \fBType\fP = FollowType\&.MoveTowards"
.br
.RI "\fITyp\&. \fP"
.ti -1c
.RI "\fBPathDefinition\fP \fBPath\fP"
.br
.RI "\fIŚcieżka\&. \fP"
.ti -1c
.RI "float \fBSpeed\fP = 1"
.br
.RI "\fIPrękość \fP"
.ti -1c
.RI "float \fBMaxDistanceToGoal\fP = \&.1f"
.br
.RI "\fIMaksymalna odległość \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
klasa \fBFollowPath\fP 


.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void FollowPath\&.Update ()"
Obiekt stworzony bez sciezki, albo ze sciezka ktora nie ma co najmniej jednego punktu\&.
.PP
Argumenty: obecna pozycja, pozycja docelowa, predkosc (skalowana przez deltaTime, aby zapewnic plynnosc animacji)\&.
.PP
Sprawdzenie czy osiagnelismy cel i mozemy przemiescic sie do kolejnego punktu\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
