.TH "FollowObject" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FollowObject \- Klasa zapewnia podążanie pasku za graczem (w odpowiedniej odległości)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "\fIAktualizacja położenia pasku zdrowia na podstawie ruchu gracza\&. \fP"
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "Vector2 \fBOffset\fP"
.br
.ti -1c
.RI "Transform \fBFollowing\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa zapewnia podążanie pasku za graczem (w odpowiedniej odległości)\&. 


.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void FollowObject\&.Update ()"

.PP
Aktualizacja położenia pasku zdrowia na podstawie ruchu gracza\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
