.TH "GameHud" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameHud \- Klasa odpowiedzialna za wyświetlanie komunikatu o zdobytych punktach za zebranie gwiazdek i dojście do nowego checkpointu (bonus czasowy)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "GUISkin \fBSkin\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa odpowiedzialna za wyświetlanie komunikatu o zdobytych punktach za zebranie gwiazdek i dojście do nowego checkpointu (bonus czasowy)\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
