.TH "IFloatingTextPositioner" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFloatingTextPositioner \- Interfejs z metodą pozwalającą pobrać położenie tekstu wyświetlanego na ekranie\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczona przez \fBCenteredTextPositioner\fP i \fBFromWorldPointTextPositioner\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "bool \fBGetPosition\fP (ref Vector2 position, GUIContent content, Vector2 size)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Interfejs z metodą pozwalającą pobrać położenie tekstu wyświetlanego na ekranie\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
