.TH "InstaKill" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstaKill \- Klasa odpowiedzialna za zabicie gracza, gdy napotka na Collider2D danego obiektu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBOnTriggerEnter2D\fP (Collider2D other)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa odpowiedzialna za zabicie gracza, gdy napotka na Collider2D danego obiektu\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
