.TH "IPlayerRespawnListener" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPlayerRespawnListener \- Interfejs odpowiedzialny za zrespawnowanie gracza w danym checkpoincie\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczona przez \fBGiveHealth\fP, \fBPointStar\fP i \fBSimpleEnemyAi\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBOnPlayerRespawnInThisCheckpoint\fP (\fBCheckpoint\fP checkpoint, \fBPlayer\fP player)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Interfejs odpowiedzialny za zrespawnowanie gracza w danym checkpoincie\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
