.TH "ITakeDamage" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITakeDamage \- Interfejs posiadający funkcją przyjmowania obrażeń o podanej wartości, zadanych przez dany obiekt\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczona przez \fBPathedProjectile\fP, \fBPlayer\fP i \fBSimpleEnemyAi\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBTakeDamage\fP (int damage, GameObject instigator)"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Interfejs posiadający funkcją przyjmowania obrażeń o podanej wartości, zadanych przez dany obiekt\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
