.TH "JumpPlatform" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JumpPlatform \- klasa \fBJumpPlatform\fP  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBControllerEnter2D\fP (\fBCharacterController2D\fP controller)"
.br
.RI "\fIUstalenie JumpMagnitude\&. \fP"
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "float \fBJumpMagnitude\fP = 20"
.br
.RI "\fIUstalenie sily skoku\&. \fP"
.ti -1c
.RI "AudioClip \fBJumpSound\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
klasa \fBJumpPlatform\fP 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
