.TH "SortParticleSystem" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SortParticleSystem \- klasa \fBSortParticleSystem\fP  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.RI "\fIDomyślnie ParticleSystem nie ma opcji ustawiania warstwy, na której ma być wyświetlany\&. \fP"
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "string \fBLayerName\fP = 'Particles'"
.br
.RI "\fINazwa warstwy \fP"
.in -1c
.SH "Opis szczegółowy"
.PP 
klasa \fBSortParticleSystem\fP 


.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void SortParticleSystem\&.Start ()"

.PP
Domyślnie ParticleSystem nie ma opcji ustawiania warstwy, na której ma być wyświetlany\&. 
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "string SortParticleSystem\&.LayerName = 'Particles'"

.PP
Nazwa warstwy 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
