.TH "StartScreen" 3 "Pn, 11 sty 2016" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StartScreen \- Klasa umożliwi ewentualne rozpoczęcie gry od ekranu startowego, a nastepnie przeniesienie do pierwszego etapu gry\&.  

.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy MonoBehaviour\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "string \fBFirstLevel\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa umożliwi ewentualne rozpoczęcie gry od ekranu startowego, a nastepnie przeniesienie do pierwszego etapu gry\&. 



.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Game\&.
